apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simedical-orthanc.fullname" . }}-config
  labels:
    {{- include "simedical-orthanc.labels" . | nindent 4 }}
data:
  # Config Orthanc NON secrète. RegisteredUsers + credentials S3 arrivent par
  # l'ExternalSecret (variables d'env ORTHANC__...). Orthanc accepte le JSON.
  orthanc.json: |-
    {{- .Values.orthanc.config | toPrettyJson | nindent 4 }}
