apiVersion: v1
kind: Service
metadata:
  name: {{ include "simedical-orthanc.fullname" . }}
  labels:
    {{- include "simedical-orthanc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
    - name: dicom
      port: {{ .Values.service.dicom.port }}
      targetPort: dicom
      protocol: TCP
  selector:
    {{- include "simedical-orthanc.selectorLabels" . | nindent 4 }}
